{% set name = "trame-quasar" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/trame-quasar-{{ version }}.tar.gz
  sha256: be25252e81e32c3ba0e04a8b85de14305a9b556e9315021ce1a8b87fa20fbd01

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - trame-client

test:
  imports:
    - trame
    - trame_quasar
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Kitware/trame-quasar
  summary: Quasar widget library for trame
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jourdain
    - psavery
